Trabajo tema 2 - Jose Luis Gomez C.
UnirCs/DWFS-PER8408-2324 pull request #109
Opened 2023-11-17 14:32 UTC by JoseLuisGomezCastellanos

2023-11-19 22:03 UTC, UnirCs commented on Tema_2/JoseLuisGomez/Cinema/cinema.js
> +                            return d;
viola la invariante del bucle

2023-11-19 22:04 UTC, UnirCs requested changes
En el ejercicio del cine violas la invariante del bucle. Reformulalo por favor para que el bucle finalice de forma lógica.

2023-11-22 23:20 UTC, JoseLuisGomezCastellanos commented on Tema_2/JoseLuisGomez/Cinema/cinema.js
> +                            return d;
Perdon, no entiendo, cual es la invariante del bucle en este caso.

2023-11-22 23:41 UTC, UnirCs commented on Tema_2/JoseLuisGomez/Cinema/cinema.js
> +                            return d;
Puede haber varias, en este caso es lo que indicas en la condición de iteración del bucle. Te contradices a ti mismo.  https://es.wikipedia.org/wiki/Ciclo_invariante
Lo he comentado varias veces en las clases y en los foros

2023-11-23 22:07 UTC, JoseLuisGomezCastellanos commented
es de esta manera correcta?

2023-11-24 00:06 UTC, UnirCs approved these changes
Mejor que como estaba antes en cuanto al tema de la invariante, sí. Apruebo y mergeo.

Ahora bien, el algoritmo da más vueltas de las necesarias y tienes en cuenta demasiadas condiciones que matemáticamente se están repitiendo... te recomiendo echar un ojo a la solución de ejemplo que dejé por el campus.

2023-11-24 00:06 UTC, merged