CAmbios Jose_luis_bautista_beltran
UnirCs/DWFS-PER8408-2324 pull request #123
Opened 2023-11-20 00:06 UTC by bautista984

2023-11-20 00:06 UTC, bautista984 commented
Profesor jesús, Por favor una ayuda al tatar de subir mis versiones, no quedan en la rama principal.

2023-11-20 17:09 UTC, UnirCs commented on package-lock.json
Este archivo hay que eliminarlo de la pr

2023-11-21 01:46 UTC, bautista984 commented on package-lock.json
> Este archivo hay que eliminarlo de la pr

De acuerdo.

2023-11-21 01:46 UTC, bautista984 commented on package.json
> Este archivo hay que eliminarlo de la pr

De acuerdo.

2023-11-21 09:04 UTC, UnirCs commented on package-lock.json
Este archivo sobra, hay que eliminarlo de la PR.

2023-11-21 09:04 UTC, UnirCs commented on package.json
Este archivo sobra, hay que eliminarlo de la PR.

2023-11-21 09:05 UTC, UnirCs requested changes
Los ejercicios están bien Jose Luis, pero falta eliminar los archivos que te dije anteriormente de la PR. Están fuera de tu carpeta.

2023-11-26 00:28 UTC, UnirCs approved these changes
OK!

2023-11-26 00:28 UTC, merged