master
UnirCs/DWFS-PER8408-2324 pull request #124
Opened 2023-11-20 01:22 UTC by carnol1989

Solution of exercises topic 2 - JavaScript

2023-11-20 17:12 UTC, UnirCs commented on Tema_2/CarlosAugustoNoleMachaca/Cinema/Cinema.js
> +                    break;
viola la invariante del bucle

2023-11-20 17:14 UTC, UnirCs requested changes
El ejercicio de filtros está bien.
El ejercicio del cine, funcionalmente también, pero tienes un break dentro de un bucle que viola su invariante. Reformúlalo para no tener condiciones de salida dispersas por el código por favor, a la larga dificulta la lectura.

Por otro lado, elimina por favor todo lo que no sea el archivo cinema.js y actividad.js (puedes dejar tu gitignore siquieres), pero todas las imagenes hay que sacarlas, esto lo hago para que el repositorio no pese más de lo necesario y no haya excesiva duplicidad.

2023-11-22 02:22 UTC, carnol1989 commented on Tema_2/CarlosAugustoNoleMachaca/Cinema/Cinema.js
> +                    break;
@UnirCs  done

2023-11-23 11:13 UTC, UnirCs approved these changes
oK!

2023-11-23 11:14 UTC, merged