Actividad 2 y Actividad 5
UnirCs/DWFS-PER8408-2324 pull request #159
Opened 2023-11-28 06:05 UTC by crisedumax

2023-11-28 06:06 UTC, crisedumax commented
pls

2023-12-02 13:20 UTC, UnirCs commented on Tema_2/Christian Eduardo Reyes A/filtros/output/merged.jpg
Todos los archivos distintos a actividad.js sobran, lo pone en el texto de la actividad

2023-12-02 13:21 UTC, UnirCs requested changes
Hola Christian:
- Del tema 2, falta eliminar todos los archivos innecesarios, si no el repo pesaria mucho con las imagenes de todos.
- Del tema 5, falta la parte del despliegue en vercel.

2023-12-09 19:18 UTC, UnirCs commented
Sigue faltando todo lo indicado

2023-12-19 17:52 UTC, UnirCs commented
Sigue faltando todo lo indicado

Se cerrará la PR en unos días por falta de inactividad

2023-12-26 23:03 UTC, UnirCs commented
Se cierra por inactividad

2023-12-26 23:03 UTC, closed without merging