Ejercicio Tema 5. Cartelera
UnirCs/DWFS-PER8408-2324 pull request #172
Opened 2023-12-04 00:31 UTC by jmanuelfrias

Ejercicio de la cartelera. Creo que he subido todo lo que hay que subir. Coméntame si falta algún archivo (que al hacer el npx create-react-app no me añade al git los ficheros que crea)

2023-12-09 19:21 UTC, UnirCs commented
El código está bien José Manuel, me falta el despliegue n vercel unicamente, no veo url

2023-12-09 19:21 UTC, UnirCs requested changes
Falta el despliegue

2023-12-19 17:52 UTC, UnirCs commented
Sigue faltando todo lo indicado

Se cerrará la PR en unos días por falta de inactividad

2023-12-20 01:50 UTC, jmanuelfrias commented
He intentado ponerlo como he hecho en la actividad individual y en vez de lanzarme la aplicación me despliega el texto que tengo en el index.js.

Pero no lo entiendo porque si lanzo npm start me sale lo correcto

2023-12-20 01:59 UTC, jmanuelfrias commented
Arreglado, está en el vercelURL.txt

2023-12-26 23:05 UTC, UnirCs approved these changes
OK!

2023-12-26 23:06 UTC, merged