EJERCICIO 5 CINEMA
UnirCs/DWFS-PER8408-2324 pull request #178
Opened 2023-12-04 23:00 UTC by Fer1196

EJERCICIO 5 

Mi IDE con Prettier a veces pone espacios en blanco en ciertos  ARCHIVOS

2023-12-09 19:37 UTC, UnirCs requested changes
Veo la app correctamente desplegada pero si te fijas en la pr no aparece el codigo. Tienes que subir los archivos aqui, y no enlaces como está ocurriendo. En esta interfaz deben aparecer todos los archivos de tu proyecto "cinema"

2023-12-11 18:28 UTC, Fer1196 commented
Correct folders

2023-12-19 17:56 UTC, UnirCs commented
¿Puedes decirme cual es tu nombre completo por favor? a partir de lo que pones en la carpeta hay varias coincidencias...

2023-12-19 18:00 UTC, Fer1196 commented
FERNANDO PATRICIO RODRIGUEZ TIGSE

2023-12-19 18:13 UTC, UnirCs approved these changes
OK!

2023-12-19 18:14 UTC, UnirCs approved these changes
OK!

2023-12-19 18:14 UTC, merged