Proyecto React inicial Luis Castillo
UnirCs/DWFS-PER8408-2324 pull request #180
Opened 2023-12-06 01:15 UTC by luiseduardocastillovelasquez

Se realiza el proyecto React donde se adiciona la pagina Home de la sala de cines

2023-12-09 19:39 UTC, UnirCs requested changes
Falta el despliegue en vercel

2023-12-18 17:08 UTC, luiseduardocastillovelasquez commented
esta es la URL del Vercel

https://luis-eduardo-castillo-vercel-mu.vercel.app

2023-12-19 17:57 UTC, UnirCs requested changes
Tienes todo el codigo dentro de mi carpeta de codigo de ejemplo, muevelo fuera por favor

2023-12-26 23:07 UTC, UnirCs commented
Se cierra por inactividad

2023-12-26 23:07 UTC, closed without merging