Ejercicios de calculadora, cine y hunde la flota
UnirCs/DWFS-PER8408-2324 pull request #193
Opened 2023-12-14 18:50 UTC by gonzalouli

He cancelado el PR anterior para cambiar unas cosillas de la traducción, ahora deberían de estar mejor.

2023-12-19 18:40 UTC, UnirCs commented
> He cancelado el PR anterior para cambiar unas cosillas de la traducción, ahora debería estar mejor.

Sí, has hecho bien, porque las que tenías antes en la calculadora no me gustaban jeje, luego te doy más feedback

2023-12-19 22:32 UTC, UnirCs commented on Tema_6/GonzaloUlibarriGarcia/HundeLaFlota.md
> +| POST        | /games/start                                  | N/A                         | N/A                                                                 | `{"status": "started"} `
en el momento en el que "creas" un juego todo debería quedar listo para operar sobre el juego. A nivel de datos el concepto de "empezar" no deberia aportar valor.
Por otro lado... es un verbo. Si queremos una logica especifica para comenzar el juego lo suyo seria especificarlo con un put o patch sobre el juego. el body nos diria que acciones realizar

2023-12-19 22:33 UTC, UnirCs commented on Tema_6/GonzaloUlibarriGarcia/HundeLaFlota.md
> +| POST        | /games/ends                                   | N/A                         | N/A                                                                 | `{"status": "ended"} `
lo mismo que antes. Por otro lado... un post para modificar un recurso?

2023-12-19 22:36 UTC, UnirCs commented on Tema_6/GonzaloUlibarriGarcia/calculadora.md
> +| GET         | /detail/{operationID} | id         | N/A                              | `{ "operands": [2,2,2], "result": 6, "operation": "add" }`             | 200 OK<br/>400 Bad Request<br/>500 Int
El ejercicio esta OK.
No obstante, no hace falta que me indiques todas las posibles respuestas que un get (en este caso details/operationId) podría tener, lo intuyo.
Por otro lado, para facilitar la integracion, seria interesante unificar la respuesta.
Por ejemplo tienes "operands" en varias pero "basis" en otras. Entiendo la razón, pero quizas seria mejor tener un mapa con claves valores donde ese mapa pudiera tener elementos con clave "operands" y "basis". De este modo la integración desde un cliente no obliga a tener que tener dos atributos cuando uno de los dos no va a ser usado, es un tema de limpieza más que nada

2023-12-19 22:40 UTC, UnirCs commented on Tema_6/GonzaloUlibarriGarcia/cinema.md
> +| POST        | /payments/{reservationID}     | N/A           | `{ "paid": true, "price": 8 , "payment":8 }`
ojo con estas construcciones, pueden llevar a error. habria que documentar claramente que el id que se espera es de una reservation ya creada. Y por otro lado, esta construccion asume que el id para recorrer la coleccion payments es el mismo que para reservations. En un mundo ideal, donde una reserva implica un pago, funcionaría... pero la realidad es que puedes tener reservas a medias, que aun no han pagado, que se cancelan.... es arriesgado esa asunción que haces.
Yo optaría mejor por incluir el id de reserva en el body, para cubrirte las espaldas.
pero a nivel de diseño rest como tal no está mal, es más bien algo conceptual

2023-12-19 22:41 UTC, UnirCs requested changes
Los ejercicios de calculadora y cine están bien Gonzalo, modifica unicamente la parte de start y end de la flota, que ahi estas usando verbos. En este caso solo hay dos acciones pero imagina un caso de uso donde hubiera muchos estados para un recurso... tener N endpoints uno con cada estado sería un poco farragoso

2023-12-20 18:17 UTC, gonzalouli commented
Perfecto, cierro este pull request y te comento los cambios que he hecho

2023-12-20 18:18 UTC, closed without merging