Tarea del tema 5
UnirCs/DWFS-PER8408-2324 pull request #197
Opened 2023-12-16 02:46 UTC by alejo-RB

2023-12-19 18:06 UTC, UnirCs requested changes
Me falta la URL de Vercel!

2023-12-26 23:09 UTC, UnirCs commented
Me sigue faltando la URL del despliegue de vercel Alejo...

2024-01-03 15:56 UTC, alejo-RB commented
Ya agregué el enlace de Vercel, perdón por la demora

2024-01-07 18:27 UTC, UnirCs approved these changes
OK!

2024-01-07 18:27 UTC, merged