feat: ejercicios Tema6 Albert Escoté
UnirCs/DWFS-PER8408-2324 pull request #213
Opened 2023-12-27 18:21 UTC by albertescote-unir

2023-12-28 13:24 UTC, UnirCs commented on Tema_6/albertescotealvarez/Calculadora.md
El diseño está bien. Quizá habría optado por un unico endpoint que en funcion del body haga una cosa u otra, pero tu planteamiento tampoco es erróneo.
Lo que sí es erróneo es ese /operations/{id}/details. ¿Qué me da, conceptualmente, ese details que no me pueda dar /operations/{id}? un GET sobre /operations/{id} debería bastar.

2023-12-28 13:25 UTC, UnirCs commented on Tema_6/albertescotealvarez/Cinema.md
OK!

2023-12-28 13:26 UTC, UnirCs requested changes
Muy bien los de cine y flota. Solo corrige lo que te he indicado en el de la calculadora.
good work!

2023-12-28 17:11 UTC, albertescote-unir commented on Tema_6/albertescotealvarez/Calculadora.md
Hola!
He optado por definir varios endpoints (uno para cada operación) porque en mi experiencia juntar varias funcionalidades en un único endpoint suele llevar a acoplamientos y inyección de dependencias innecesarias. Quizá justo en este caso, que no es muy complejo, mi solución es más "overengineering" que otra cosa. Pero como estoy acostumbrado a trabajar de estar forma, he optado por esta solución. 

En cuanto al details tienes toda la razón, ya lo he arreglado.

Gracias por el feedback!

2024-01-07 18:28 UTC, UnirCs approved these changes
OK!

2024-01-07 18:28 UTC, merged