Entrega actividad opcional tema 6
UnirCs/DWFS-PER8408-2324 pull request #216
Opened 2024-01-04 17:29 UTC by SalvaRoca

2024-01-07 18:35 UTC, UnirCs commented on Tema_6/Salva Roca/Calculadora.md
> +| POST        | /calculate | N/A           | `{"operation": "add", "operands": [2, 2]}` | `{"result": 4, "calculationId": 1}`                    | 201 Created<br/>400 Bad Request<br/>500 Internal Ser
Esto es un verbo.
Hay que pensar en el "objeto" o "concepto" que la api maneja. Podría ser "operación" . crear operacion, obtener operacion, eliminar operacion...

2024-01-07 18:35 UTC, UnirCs commented on Tema_6/Salva Roca/Calculadora.md
> +| GET         | /memory    | calculationId | N/A                                        | `{"operation": "add", "operands": [2, 2], "result": 4` | 200 OK<br/>400 Bad Request<br/>404 Not Found<br/>500
de nuevo un verbo.
lo que queremos es obtener el detalle de una operacion ya hecha.

2024-01-07 18:36 UTC, UnirCs requested changes
La de la calculadora esta flojilla.
Viendo lo bien que te han quedado las otras dos es raro!!
aun asi good work.

2024-01-08 06:28 UTC, SalvaRoca commented
> La de la calculadora esta flojilla. Viendo lo bien que te han quedado las otras dos es raro!! aun asi good work.

Por intentar simplificar la API de la calculadora al máximo, ¡olvidé lo básico! Ahora he dejado un único endpoint `/calculation` para las peticiones POST (que realizan el cálculo y lo guardan en memoria) y GET (que recuperan los cálculos de la memoria).

2024-01-09 22:00 UTC, UnirCs commented on Tema_6/Salva Roca/Calculadora.md
Está estupendo con "calculation" pero recuerda que... en la uri tenemos la colección por lo que sería "calculations"

2024-01-09 22:00 UTC, UnirCs requested changes
Añade una "s" y todo listo :D

2024-01-10 21:22 UTC, UnirCs approved these changes
OK!

2024-01-10 21:22 UTC, merged