Ejercicios tema 3, 4, 5
UnirCs/DWFS-PER8408-2324 pull request #217
Opened 2024-01-05 20:22 UTC by Joseluisjlgc

2024-01-07 18:33 UTC, UnirCs commented on Tema_6/JoseLuisGomezCastellanos/HundeLaFlota.md
> +| GET                                    | /users/{userId}/matchs/{matchId}/play               | N/A      | N/A                                                                | `{matchId: "646", "use
play es un verbo :/

2024-01-07 18:33 UTC, UnirCs commented on Tema_6/JoseLuisGomezCastellanos/HundeLaFlota.md
> +| PATCH           | /users/{userId}/matchs/{matchId}/play | N/A           | `{"board1": [{"state": "Disparado"}`          | `{"board1": [{"id": "34", "state": "Disparado", "boatId": "2boat2"}`
play es un verbo.

Hay que darle una vuelta a esto para no usarlos.

2024-01-07 18:34 UTC, UnirCs requested changes
Tema 5: Falta enlace de Vercel (o no lo he visto)
Tema 6: En Hunde la Flota usas verbos en alguna URI, hay que reemplazarlos para que la propia logica y semantica de la api sea suficiente.

2024-01-12 08:32 UTC, UnirCs commented
Se cerrará la PR por inactividad a final de semana

2024-01-14 01:44 UTC, Joseluisjlgc commented
Se refiere al "play" en  "/users/{userId}/matchs/{matchId}/play", eso es un a partida en progreso, no puedo usar algo que no haya sido identificado como un actor?

2024-01-14 11:29 UTC, UnirCs commented
Sí, me refiero a ese endpoint. El problema es que asocias una acción que es propia del dominio a la definición de la API. En la API tenemos recursos, los cuáles los tienes bien identificados (users, matchs, etc...) y la API debe reflejar operaciones con esos recursos mediante los verbos de los métodos HTTP, es decir, GET, POST, PUT, PATCH, DELETE... 

En este contexto, tienes que hacerte la pregunta.... ¿qué es "iniciar una partida"? ¿Es crear un recurso partida? ¿Es modificar una partida existente y poner un atributo interno "started" a true? Eso depende del diseño de recursos que tú hagas pero en cualquier caso lo que tienes que identificar es si "iniciar una partida" crea un nuevo recurso partida o lo actualiza. Si lo crea, la operación sería POST y si actualiza una existente sería PUT o PATCH en función de si se actualiza la información de la partida completamente o de forma parcial. Lo más normal es que sea de forma parcial por lo que usaríamos PATCH /users/{userId}/matchs/{matchId} y en el body tendríamos algún atributo "started" o algo similar y se pondría a true.

Lo que no es buena práctica es trasladar la complejidad de mi implementación o caso funcional a la API. La api está basada en recursos y lo que se expone son operaciones sobre ellos siguiendo la semántica de las operaciones HTTP. Imagina que tuvieras 20 estados para una partida. ¿Harías 20 endpoints? Estarías trasladando la complejidad del caso de uso o de la implementación a la parte de diseño.

A eso me refiero. Con cualquier duda me dices

2024-01-18 00:23 UTC, UnirCs approved these changes
OK!

2024-01-18 00:24 UTC, merged