Tema - 6
UnirCs/DWFS-PER8408-2324 pull request #220
Opened 2024-01-10 09:59 UTC by jesussanchezalvarez3

2024-01-10 21:24 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/calculadora/calculadora.md
Tiene que haber cierta relación entre recursos.
Si yo creo con POST /suma, tengo que recuperar con GET /suma/{id}. Si no no hay coherencia entre los recursos.

Por otro lado, siempre en plural. /sumas, /restas ....

2024-01-10 21:25 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/cine/cine.md
> +DELETE 	/peliculas 	N/A 	{ 	{true} 	200 OK 
Siempre hay que pasar un path param para eliminar
DELETE /peliculas/{idPelicula}

2024-01-10 21:25 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/cine/cine.md
> +PUT 	/peliculas 	N/A 	{ 
Siempre hay que pasar un path param para actualizar
PUT /peliculas/{idPelicula}

2024-01-10 21:25 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/cine/cine.md
> +POST 	/pago/{id_Reserva} 	id 	N/A 	OK 	200 OK 
Siempre en plural, /pagos

2024-01-10 21:25 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/hunde la flota/flota.md
> +POST 	/partida 	N/A 	{ 	{ 	200 OK 
Siempre en plural

2024-01-10 21:25 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/hunde la flota/flota.md
> +DELETE 	/partida/{id} 	id 	N/A 	OK 	200 OK 
Plural

2024-01-10 21:25 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/hunde la flota/flota.md
> +PATCH iniciar o finalizar 	/partida/{id} 	N/A 	{ 	{ 	200 OK 
Plural :D

2024-01-10 21:26 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/hunde la flota/flota.md
> +GET 	/barco 	{id} 	N/A 	{ 	200 OK 
Ok pero pon la uri bien /barcoS/{id}

2024-01-10 21:27 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/hunde la flota/flota.md
> +POST 	/disparar 	N/A 	{ 	OK 	200 OK 
ufff esto es un verbo.
Piensalo mejor. ¿Qué es un disparo? ¿Es actualizar parte del estado de una partida? Entonces... PATCH /partidas/{idPartida} ... por ejemplo, puede haber otras opciones.

2024-01-10 21:27 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/hunde la flota/flota.md
> +POST 	/barco 	N/A 	{ 	{resultado:{ 	200 ok 
plural :(

2024-01-10 21:28 UTC, UnirCs requested changes
Te he indicado un par de cosillas.
En líneas generales no está mal pero hay que pulir algún detalle

2024-01-12 07:57 UTC, jesussanchezalvarez3 commented
Cambios realizados

2024-01-12 08:23 UTC, UnirCs commented on Tema_1/Julian_Rojas/cv/img/SandraLopez.png
No toques los archivos de Sandra, está feo

2024-01-12 08:24 UTC, UnirCs commented on Tema_1/Julian_Rojas/cv/img/.SandraLopez.png.icloud
No añadas nada aquí

2024-01-12 08:25 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/calculadora/calculadora.md
OK.
No hace falta que lo cambies, pero para futuros... un query param no es un path param.
Si yo tengo /sumas/{id}, no tengo que especificar "id" como query param porque no lo es. Es un path param. En la seccion de query params ponemos parametros opcionales de busqueda en caso de que se permitan

2024-01-12 08:26 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/cine/cine.md
> +DELETE|/peliculas|N/A|{|{true}|200 OK 
Sigue faltando el id sobre el cual eliminamos

2024-01-12 08:26 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/cine/cine.md
> +PUT|/peliculas|N/A|{|
Sigue faltando el id sobre el cual eliminamos

2024-01-12 08:26 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/cine/cine.md
> +DELETE|/peliculas|N/A|{|{true}|200 OK 
Por otro lado.... los bodys no tienen mucho sentido, no?

2024-01-12 08:28 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/cine/cine.md
> +POST|/pagos/{id_Reserva}|id|N/A|OK|200 OK 
No es habitual pasar un path param cuando creo un recurso. Si estoy creando el pago, no tiene mucho sentido pasarle el id.
En este caso entiendo por que lo haces aunque seria mejor que fuese en el body, pero no está "del todo mal", aunque no es la mejor de las prácticas

2024-01-12 08:29 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/hunde la flota/flota.md
> +GET|/barcos|{id}|N/A|{|200 OK 
barcos/{id} es el endpoint. Los query param no se especifican en la URI.
Los path param si.

2024-01-12 08:30 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/hunde la flota/flota.md
> +GET|/barcos|{id}|N/A|{|200 OK 
Si quieres meter query prams en este endpoint podrias tener jugador, partida, etc.
Revisa mi api de products que mostre en clase para ver esto en el metodo GET /products

2024-01-12 08:30 UTC, UnirCs requested changes
Siguen faltando algunas cosas Jesús.
Por otro lado, no toques archivos de otro compañero. Puedes ver si lo estás haciendo en la vista de la PR.
Si tienes cualquier duda dime ;)

2024-01-12 11:33 UTC, jesussanchezalvarez3 commented on Tema_1/Julian_Rojas/cv/img/.SandraLopez.png.icloud
no se que habrá pasado, pero no toqué nada de eso...

2024-01-13 20:09 UTC, UnirCs commented on Tema_6/Jesus Sanchez Alvarez/calculadora/calculadora.md
> +GET|/detalle/{id_operacion}|id|N/A|{resultado:{|200 ok 
Este te sobraría, simplemente te lo comento

2024-01-13 20:09 UTC, UnirCs approved these changes
Te sobra un endpoint en la calculadora y en el PUT de /peliculas un id, pero el resto OK! Abreme luego otra PR para modificar eso, asi ya te contabilizo esto.

2024-01-13 20:10 UTC, merged