Subir Cambios Tema 06
UnirCs/DWFS-PER8408-2324 pull request #231
Opened 2024-01-20 22:16 UTC by bautista984

Subir archivos md calculadora, cinema y hunde la flota

2024-01-22 13:02 UTC, UnirCs commented on Tema_6/Jose_Luis_Bautista_Beltran/Calculadora.md
> +| Método HTTP | URI | Query Params | Request Body | Response Body | Códigos HTTP de respuesta |
La parte de "api/calculator" por estándar no está mal incluirla aunque si un micro expone solo operaciones de "calculator" no tiene sentido incluir "calculator" en todos los endpoints. Por otro lado, todos los recursos tienen que indicarse en plural en las uris (additions, substractions, divisions...) Lo tienes todo en singular.

2024-01-22 13:03 UTC, UnirCs commented on Tema_6/Jose_Luis_Bautista_Beltran/Cinema.md
> +| Método HTTP | URI | Query Params | Request Body | Response Body | Códigos HTTP de respuesta |
Lo mismo que en el caso de la calculadora

2024-01-22 13:05 UTC, UnirCs commented on Tema_6/Jose_Luis_Bautista_Beltran/Hunde_la_flota.md
> +| GET | /api/battlenaval/info/{game_id}/ | {game_id=1} | ``-`` | ``[{"player1":"name1", "ships":[{"ship":1,"position":"A1,A4"},{"ship":2,"position":"B2,B4"},{"ship":3,"position":"E5,G5"}, {"ship":4,"
ese "info" no aporta nada relevante, es más, es redundante con el tipo de operación y con la uri si fuese correcta: GET /api/battlenaval/games/{gameId}

2024-01-22 13:05 UTC, UnirCs commented on Tema_6/Jose_Luis_Bautista_Beltran/Hunde_la_flota.md
> +| Método HTTP | URI | Query Params | Request Body | Response Body | Códigos HTTP de respuesta |
Lo mismo para el tema de los plurales que en los otros 2 ejercicios

2024-02-02 14:17 UTC, UnirCs commented
Se cerrara la PR a finales de semana por inactividad.

2024-02-03 10:40 UTC, bautista984 commented
Profe Jesús, seguidas sus recomendaciones,

2024-02-04 11:07 UTC, UnirCs commented on Tema_6/Jose_Luis_Bautista_Beltran/Hunde_la_flota.md
> +| PUT | /api/state/{game_id}/ | {game_id=1} | ``{"state":"start"} or {"state":"stop"}`` | ``{"game_id":1,"state":"start"} or {"game_id":1,"state":"stop"}`` | 200 OK 400 Bad Request 404 Not Found 500
Esto es un poco extraño, si solo quieres modificar el state tendrias que usar un patch sobre /api/games/{gameId}

2024-02-04 11:08 UTC, UnirCs commented on Tema_6/Jose_Luis_Bautista_Beltran/Calculadora.md
> +| POST | /api/sqrt/ |  | ``{"operator1" : 4 ,"operator2" : 2}`` | ``{"id": 5, "result":2}`` | 201 Created 400 Bad Request 404 Not Found 500 Internal Error |
singular!

2024-02-04 11:08 UTC, UnirCs commented on Tema_6/Jose_Luis_Bautista_Beltran/Calculadora.md
> +| POST | /api/pow/ | - | ``{"operator1" : 5 ,"operator2" : 2}`` | ``{"id": 6, "result":25}`` | 201 Created 400 Bad Request 404 Not Found 500 Internal Error |
singular!

2024-02-04 11:08 UTC, UnirCs requested changes
Dejo tres comentarios más

2024-02-10 22:04 UTC, bautista984 commented
Se ha ajustado las recomendaciones

2024-02-18 06:07 UTC, UnirCs approved these changes
OK!

2024-02-18 06:07 UTC, merged