Ejercicios tema 6
UnirCs/DWFS-PER8408-2324 pull request #233
Opened 2024-01-21 11:59 UTC by gorkagg10

2024-01-22 13:06 UTC, UnirCs commented on Tema_6/GorkaGonzalezGomez/calculadora.md
> +| Método HTTP | URI                         | Query Params | Cuerpo de la petición                               | Cuerpo de la respuesta
Si tu api solo expone "operations", tener "operations" en todas las uris es redundante. Si ofreciese "operations" y "casas" pues podría tener sentido distinguir, pero si no...

2024-01-22 13:09 UTC, UnirCs requested changes
El del cine y de los barcos están genial, solo falta retocar el de la calculadora.

2024-01-22 18:59 UTC, gorkagg10 commented on Tema_6/GorkaGonzalezGomez/calculadora.md
> +| Método HTTP | URI                         | Query Params | Cuerpo de la petición                               | Cuerpo de la respuesta
Okey, gracias por el feedback. Haré otro intento mirandolo de esa forma.

2024-01-22 19:17 UTC, gorkagg10 commented
He añadido los cambios propuestos. ¡Gracias otra vez!

2024-01-22 20:48 UTC, UnirCs reviewed
OK T6. Del 8 veo que faltan endpoints por implementar aún.

2024-02-02 14:17 UTC, UnirCs commented
Se cerrara la PR a finales de semana por inactividad.

2024-02-05 00:15 UTC, UnirCs commented
PR Cerrrada por inactividad

2024-02-05 00:15 UTC, closed without merging