Actividad 6
UnirCs/DWFS-PER8408-2324 pull request #240
Opened 2024-01-24 21:37 UTC by ACanellasUNIR

Actividad 6

2024-01-24 21:39 UTC, ACanellasUNIR commented
Actividad 6

2024-01-25 09:27 UTC, UnirCs commented on Tema_6/AntonioCanellas/calculadora.md
> +| Método HTTP | URI        | Query Params | Request Body         | Response Body                                                | Códigos HTTP de respuesta |
Nunca usamos verbos en las URIs, orientalo a recursos, y no a operaciones que es como sería en un servicio web. "Sumas", "restas, "muplitiplicaciones" -> en este caso tendrias N POSTs y N GET, 1 por cada recurso identificado.
Otra opcion, trabajar solo con el recurso "operaciones" donde tendrias que meter el tipo en el body del POST y tendrías por tanto 1 POST y 1 GET.

El get que pones es sobre el recurso "detail" que no tiene ningun post asociado por lo que no tiene sentido.

2024-01-25 09:28 UTC, UnirCs commented on Tema_6/AntonioCanellas/cinema.md
> +| POST        | /hall             | N/A          | {"rows":10,"columns":10}                                                                                          | {"hallId":1}  | 201,400,500
Plural, no singular. En las uris las colecciones siempre en plural.

2024-01-25 09:28 UTC, UnirCs commented on Tema_6/AntonioCanellas/cinema.md
> +| POST        | /book             | N/A          | {userId:1, hallId:1, "Time":"12:30",row:3,column:5                                                                | bookId        | 201,400,500
Plural

2024-01-25 09:28 UTC, UnirCs commented on Tema_6/AntonioCanellas/cinema.md
> +| POST        | /pay              | N/A          | {userId:1,bookId1}                                                                                                | payId         | 200,400,500
No hay que usar verbos, y siempre plural

2024-01-25 09:29 UTC, UnirCs requested changes
Revisa los comentarios Antonio, también de cara a la API del laboratorio

2024-02-02 14:16 UTC, UnirCs commented
Se cerrara la PR a finales de semana por inactividad.

2024-02-05 00:15 UTC, UnirCs commented
PR Cerrrada por inactividad

2024-02-05 00:15 UTC, closed without merging