Entrega Tema 6 Calculadora y Cinema
UnirCs/DWFS-PER8408-2324 pull request #246
Opened 2024-01-26 14:24 UTC by sergioAlvarezUNIR

2024-01-26 23:54 UTC, UnirCs commented on Tema_5/00_Resources/Codigo de ejemplo/unir-delivery-hooks-and-router/src/App.js
Tienes que revertir los cambios en este archivo, que es mío

2024-01-26 23:55 UTC, UnirCs commented on Tema_6/Sergio_Alvarez_Uribe/Calculadora.md
> +| POST                                   | /operations            | N/A           | `{"operations": "add", "operands": [2, 2, 2]}`                      | `{"resultsId": 1, "results": 6}`
OK, aunque dado que el endpoint es el mismo, no hace falta que lo repitas N veces con todos los posibles bodies. No tienes que cambiar nada ahora, simplemente lo comento para el futuro.

2024-01-26 23:55 UTC, UnirCs commented on Tema_6/Sergio_Alvarez_Uribe/Cinema.md
> +| POST                                   | /operations            | N/A           | `{"operations": "subs", "operands": [2, 2, 2]}`                     | `{"resultsId": 2, "results": -2}`
Esto se te ha colado del otro

2024-01-26 23:56 UTC, UnirCs requested changes
Los ejercicios están correctos Sergio, revierte el cambio en mi archivo y todo OK

2024-01-28 19:59 UTC, sergioAlvarezUNIR commented
Hola profesor Jesús, supuestamente ya pude corregir el cambio involuntario que había realizado en el archivo de ejemplo, sin embargo no estoy seguro si quedó bien, por favor tenerme un poco de paciencia usando Git y GitHub, agradezco cualquier retroalimentación.

2024-01-31 22:39 UTC, UnirCs approved these changes
OK! Todo correcto ahora :D

2024-01-31 22:39 UTC, merged