Tema 5
UnirCs/DWFS-PER8408-2324 pull request #250
Opened 2024-01-29 19:53 UTC by sguerrerosilva

Entrega ejercicio tema 5 parte 1.

2024-01-31 02:52 UTC, sguerrerosilva commented
Se suben cambios adicionales del tema 6.

2024-01-31 22:45 UTC, UnirCs commented on Tema_6/SebastianGuerrero/HundeLaFlota.md
> +| POST        | /ships/game/{idGame}               | N/A          | `{"finalCoordinated":"A1","initialCoordinate":"A1","type":1}`
El "game" no es un subrecurso de "ships". Es al revés. Lo correcto sería /games/{gameId}/ships.

2024-01-31 22:46 UTC, UnirCs commented on Tema_6/SebastianGuerrero/HundeLaFlota.md
> +| GET         | /ships/user/{idUser}/game/{idGame} | N/A          | N/A
Lo mismo, la correlacion de recursos no es correcta
/games/{idGame}/users/{idUser}/ships. La ultima parte de la URI hace referencia al recurso que queremos tratar.

2024-01-31 22:47 UTC, UnirCs commented on Tema_6/SebastianGuerrero/HundeLaFlota.md
> +| POST        | /shot                              | N/A          | `{"coordinated":"B3","idPlayerShot":1}`
Siempre plurales

2024-01-31 22:49 UTC, UnirCs commented on Tema_6/SebastianGuerrero/HundeLaFlota.md
En líneas generales hay algo no del todo correcto y es que tienes endpoints con subrecursos aislados, como DELETE ships/{idShip}. Si "ships" fuese un recurso de primer nivel, estaría todo OK. pero a nivel API no se entiende que un ship no esté asociado a una partida, o hacer referencia a un ship fuera del contexto de una partida (por mucho que tú en una db puedas obtener un ship cualquiera con un SELECT . Por lo tanto liga siempre subrecursos a recursos. En la que te he comentado sería, DELETE /games{idGame}/ships/{idShip}

2024-01-31 22:49 UTC, UnirCs commented on Tema_6/SebastianGuerrero/cinema.md
> +| POST                            | /bookings/{idBooking}/payment | N/A          | `{"amount":200,"paymentType":"Tarjeta de credito","transactionStatus":"Confirmado"}`
Siempre plural, "payments"

2024-01-31 22:50 UTC, UnirCs requested changes
Ejercicio T5 OK.
Para los del t6 revisa mis comentarios por favor, también de cara al laboratorio. Cualquier duda me dices.

2024-02-01 00:21 UTC, sguerrerosilva commented
Hola Jesus, gracias por tu retroalimentación concuerdo con los cambios que mencionas muchas gracias, te subo los cambios con las observaciones mencionadas.

2024-02-02 13:52 UTC, UnirCs approved these changes
OK! Ahora está perfecto. Gwork!

2024-02-02 13:52 UTC, merged