Deber6
UnirCs/DWFS-PER8408-2324 pull request #261
Opened 2024-02-18 03:32 UTC by vicenteeduardo-rodriguez043

Deber 6 de la API REST calculadora, cinema y jurgo hunder

2024-02-18 06:11 UTC, UnirCs commented on Tema_6/Vicente_Rodriguez_Echeverria/Hunde de la Flota/hunde.md
> +| POST        | /api/partidas/{id}/iniciar                      | -            | -
esto deberia ser un patch, ya que solo vas a modificar unos pocos atributos, no estás creando nada como tal. Ademas, usas un verbo en la URI.

2024-02-18 06:11 UTC, UnirCs commented on Tema_6/Vicente_Rodriguez_Echeverria/Hunde de la Flota/hunde.md
> +| POST        | /api/partidas/{id}/finalizar                    | -            | -
Lo mismo que en el caso anterior

2024-02-18 06:11 UTC, UnirCs commented on Tema_6/Vicente_Rodriguez_Echeverria/Hunde de la Flota/hunde.md
> +| GET         | /api/partidas/{id}/detalle                      | -            | -
¿Qué aporta ese /detalle que no tenga ya /api/partidas/{id} ? es redundante

2024-02-18 06:12 UTC, UnirCs requested changes
Calculadora y cine OK. Para el de los barcos revisa lo indicado porfa.

2024-02-23 18:05 UTC, vicenteeduardo-rodriguez043 commented
Saludo estimado Jesús, mil disculpas que no haya podido corregir las correcciones y subir de inmediato, pero por asunto laborar se me ha complicado continuar ya que en ambos trabajos que tengo estamos cerrando fin de periodo y nos tiene generando y subiendo informes. Pero ya corregí la parte de cambiar los POST por PATCH, es verdad estoy modificando un paramento y no todos y en lo que respecta la end point GET api/partidas/{id}/detalle, lo agregué porque pensé que se podía agregar también api/partidas/{id}/estadistica, api/partidas/{id}/movimientos o api/partidas/{id}/resume, pero como no se está pidiendo aquello ya lo dejé como api/partidas/{id}.

De antemano gracias por el tiempo en revisar mis actividades académicas y espero ojalá desarrollar todas dentro del plazo dado.

________________________________
De: UNIR - Software Engineering ***@***.***>
Enviado: jueves, 22 de febrero de 2024 13:47
Para: UnirCs/DWFS-PER8408-2324 ***@***.***>
Cc: vicente eduardo rodriguez echeverria ***@***.***>; Author ***@***.***>
Asunto: Re: [UnirCs/DWFS-PER8408-2324] Deber6 (PR #261)

No suele recibir correos electrónicos de ***@***.*** Por qué esto es importante<https://aka.ms/LearnAboutSenderIdentification>

Recuerda revisar esto Vicente!

—
Reply to this email directly, view it on GitHub<https://github.com/UnirCs/DWFS-PER8408-2324/pull/261#issuecomment-1960051600>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BEDQMIV5BUBVZZHUSCDLZM3YU6HFNAVCNFSM6AAAAABDN2AUEWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRQGA2TCNRQGA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-02-25 21:50 UTC, UnirCs commented on Tema_6/Vicente_Rodriguez_Echeverria/Hunde de la Flota/hunde.md
> +| PATCH        | /api/partidas/{id}/inicio                      | -            | -
Sigues teniendo un endpoint atado a una casuistica.
Realmente la diferencia a nivel de implementacion entre /inicio y /fin es minima. Siempre cambiarías el valor de algún atributo del recurso. Por lo tanto puedes tener un único PATCH /api/partidas/{id}

Si tuvieras 50 casuisticas (aqui solo son 2 por simplicidad), tendrías y mantendrías 50 endpoints en tu código?

2024-02-25 21:50 UTC, UnirCs commented on Tema_6/Vicente_Rodriguez_Echeverria/Hunde de la Flota/hunde.md
> +| PATCH        | /api/partidas/{id}/fin                    | -            | -
Lo mismo de arriba

2024-02-25 21:51 UTC, UnirCs commented on Tema_8/Vicente-Rodriguez-Echeverria/calculadora/src/main/java/com/unir/calculadora/controller/CalculatorController.java
> +    @GetMapping("/calculators")
Aquí no estás implementando la API que definiste en Calculadora.md en el tema 6 :(

2024-02-25 21:51 UTC, UnirCs requested changes
En tema de diseño aún hay algo pendiente. Revisa tambien el ejercicio extra de este tema que puse.
En cuanto al tema 8, la implementacion que has hecho no sigue la api que definiste, es totalmente distinta.

2024-02-28 23:33 UTC, UnirCs commented
Se cierra PR por inactividad

2024-02-28 23:33 UTC, closed without merging