Probelemas con el builder en Oper
UnirCs/DWFS-PER8408-2324 pull request #267
Opened 2024-02-22 16:17 UTC by Joseluisjlgc

Tengo una duda profesor el proyecto no esta compilando correctamente por un problema en src\main\java\com\math\calculator\model\pojo\Oper parece un problema con el builder, creo que no lo estoy implementado bien.

2024-02-22 18:48 UTC, UnirCs commented on Tema_8/JoseLuisGomezCastellanos/Calculadora/src/main/java/com/math/calculator/model/pojo/Oper.java
> +	public static class builder() {
todo esta clase ad-hoc sobra. La anotacion builder genera el constructor estático por ti.

2024-02-22 18:48 UTC, UnirCs requested changes
Eliminando la clase anidada que tienes todo debería ir bien,

2024-02-27 21:53 UTC, Joseluisjlgc commented
Perdon por la demora en la respuesta, he estado enfermo, si es posible que el problema es el builder, pero si deseo sacar los valores de fecha y resultado donde podria hacerlo, cual es la recomendacion, los hallo fuera de la clase y los envio al builder como los demas?

2024-02-27 22:42 UTC, UnirCs commented
Las anotaciones
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder

Te estan dando getters para todos los atributos, tambien setters y constructores sin argumentos y con argumentos. Y si quieres un objeto con unos atributos si y otros no, tienes el builder de la anotacion, Oper.builder().`property`.build();

Deberías tener todo lo necesario con eso, ¿que echas en falta?

2024-02-28 22:43 UTC, Joseluisjlgc commented
fecha y resultado no son puestos por el usuario, teniendo en cuenta buenas practicas donde se deberian calcular?

2024-02-28 22:49 UTC, Joseluisjlgc commented
perdon, tambien una pregunta, y como mi tutora parece que va estar ocupada estos dias, necesito confirmar si es posible cambiar la fecha de los examenes, ya me llegaron unos resultados del laboratorio y confirmaron que tengo denge

2024-02-28 23:00 UTC, UnirCs commented
> perdon, tambien una pregunta, y como mi tutora parece que va estar ocupada estos dias, necesito confirmar si es posible cambiar la fecha de los examenes, ya me llegaron unos resultados del laboratorio y confirmaron que tengo denge

Este no es el foro para eso, por favor debes llamar al teléfono de soporte en hora laboral para que te indiquen.

2024-02-28 23:01 UTC, UnirCs commented
> fecha y resultado no son puestos por el usuario, teniendo en cuenta buenas practicas donde se deberian calcular?

En el momento de la creación de cada operación, ¿no? La fecha con un new Date(); y el resultado... pues el resultado de la operación

2024-03-10 23:22 UTC, UnirCs commented
Ya no se aceptan envíos.

2024-03-10 23:22 UTC, closed without merging