Tarea 06
UnirCs/DWFS-PER8408-2324 pull request #270
Opened 2024-02-25 04:58 UTC by LuisRG3

2024-02-25 21:39 UTC, UnirCs commented on Tema_6/LuisAlbertoRuizGuzman/Cinema.md
> +| DELETE      | /reservas/       | -            | -                           |  {"accion":"Eliminar"         | 200                       |
No debe haber dos identificadores de recurso juntos porque no se sabe qué es qué.
 DELETE /reservas/1/1 . Esto no es claro.

Si quiero eliminar la reserva 1 del usuario 1, DELETE /usuarios/1/reservas/1 o DELETE /reservas/{idReserva}

2024-02-25 21:40 UTC, UnirCs commented on Tema_6/LuisAlbertoRuizGuzman/Cinema.md
> +| PATCH       | /reservas/       | -            | {"salaId": #########,       |   {"reservaId": ###########,  | 200                       |
Lo mismo que en el caso anterior

2024-02-25 21:40 UTC, UnirCs commented on Tema_6/LuisAlbertoRuizGuzman/HundeLaFlota.md
> +| POST        | /partidas/{id}/  | -            | {"jugadorIniciador": "user1"}   |   {"mensaje": "ha comenzado",   | 201                       |
Un verbo viola los estándares de REST. ¿Si tuvieras 50 estados tendrías 50 endpoints?

2024-02-25 21:40 UTC, UnirCs commented on Tema_6/LuisAlbertoRuizGuzman/HundeLaFlota.md
> +| POST        | /partidas/{id}/  | -            | {"jugadorFinalizador": "user1"} |   {"mensaje": "ha finalizado",  | 201                       |
Un verbo viola los estándares de REST. ¿Si tuvieras 50 estados tendrías 50 endpoints?

Un único pATCH con diferentes bodies es más que suficiente.

2024-02-25 21:41 UTC, UnirCs requested changes
En líneas generales no está mal, pero revisa lo que te he comentado.

2024-02-27 07:38 UTC, LuisRG3 commented on Tema_6/LuisAlbertoRuizGuzman/Cinema.md
> +| DELETE      | /reservas/       | -            | -                           |  {"accion":"Eliminar"         | 200                       |
Buen día profesor, si entiendo error mío ya lo corregí.

2024-02-27 07:39 UTC, LuisRG3 commented on Tema_6/LuisAlbertoRuizGuzman/HundeLaFlota.md
> +| POST        | /partidas/{id}/  | -            | {"jugadorFinalizador": "user1"} |   {"mensaje": "ha finalizado",  | 201                       |
Si creo que me deje llevar por los verbos iniciar y eliminar, pero si se quiere ver mas amplio serian un estado dentro del patch con el que actualizaría la partida, gracias ahora esta ams claro.

2024-02-27 07:41 UTC, LuisRG3 commented
Ya corregí los cambios, si pudiera revisarlos para ver si están bien antes del examen seria genial muchas gracias profesor.

2024-02-27 09:08 UTC, UnirCs approved these changes
OK! Todo correcto

2024-02-27 10:07 UTC, UnirCs approved these changes
OK! Todo correcto

2024-02-27 10:07 UTC, merged