Ejercicios Tema 1
UnirCs/DWFS-PER8408-2324 pull request #29
Opened 2023-11-07 03:57 UTC by AlanJuker

2023-11-07 23:34 UTC, UnirCs commented on Tema_1/AlanGuijarro/cinema/index.html
> +    <h1 class="text-center" style="margin-right: 100px;">Cinema Seat Selection</h1>
Estilo inline innecesario

2023-11-07 23:35 UTC, UnirCs requested changes
Todo estupendo, salvo por el estilo inline, revisalo porfa

2023-11-08 01:25 UTC, AlanJuker commented on Tema_1/AlanGuijarro/cinema/index.html
> +    <h1 class="text-center" style="margin-right: 100px;">Cinema Seat Selection</h1>
Corregido!

2023-11-08 08:29 UTC, UnirCs approved these changes
oK!

2023-11-08 08:29 UTC, merged