Cinema terminado
UnirCs/DWFS-PER8408-2324 pull request #40
Opened 2023-11-08 15:11 UTC by alejo-RB

2023-11-08 16:42 UTC, UnirCs commented on Tema_1/Alejandro_Rodriguez_Benalcazar/Cinema/styles.css
> +.f1__c1,    .f2__c1,    .f3__c1,    .f4__c1,    .f5__c1,
Este tipo de cosas pueden tener sentido si queremos que cada asiento de cada fila sea diferente a otro en términos de estilo.

A priori no creo que sea necesario detallar tanto, hasta nivel de asiento, pero no se como lo has pensado en tu cabeza asi que compro

2023-11-08 16:43 UTC, UnirCs requested changes
ok!

2023-11-08 16:43 UTC, UnirCs approved these changes
ok!

2023-11-08 16:43 UTC, merged

2023-11-09 03:25 UTC, alejo-RB commented on Tema_1/Alejandro_Rodriguez_Benalcazar/Cinema/styles.css
> +.f1__c1,    .f2__c1,    .f3__c1,    .f4__c1,    .f5__c1,
Se me complicó hacer el cambio de color sin usar JavaScript, y para que pudiera funcionar se me ocurrió hacerlo así porque si no especifico con nombres distinto no se comportaban como asientos únicos y se marcaban asientos que no quería que se marcaran. Trataré de mejorarlo y hacerlo más limpio.