Ejercicio CV
UnirCs/DWFS-PER8408-2324 pull request #45
Opened 2023-11-08 18:56 UTC by EMIsDev

2023-11-08 20:58 UTC, UnirCs commented on Tema_1/Emiliano_Albamonte_Barber/cinema/index.html
Falta el input para seleccionar el numero de asientos, no?

2023-11-08 20:59 UTC, UnirCs requested changes
Están OK Emiliano, pero falta el input para el número de asientos en el del cine

2023-11-08 23:51 UTC, EMIsDev commented on Tema_1/Emiliano_Albamonte_Barber/cinema/index.html
Okey puedo ponerlo sin problema, aunque quería hacerlo con un onClick o algo por el estilo cuando agregaramos js.

2023-11-09 15:11 UTC, UnirCs approved these changes
OK!

2023-11-09 15:11 UTC, merged