ejercicio filtros hecho
UnirCs/DWFS-PER8408-2324 pull request #54
Opened 2023-11-10 19:24 UTC by EMIsDev

2023-11-11 17:48 UTC, UnirCs commented on Tema_2/Emiliano_Albamonte_Barber/filtros/ImageHandler.js
eliminar

2023-11-11 17:48 UTC, UnirCs commented on Tema_2/Emiliano_Albamonte_Barber/filtros/actividad.js
eliminar

2023-11-11 17:48 UTC, UnirCs requested changes
El ejercicio está bien Emiliano, quita los archivos que no pedía y está listo para mergear.

2023-11-13 01:11 UTC, UnirCs commented on Tema_2/Emiliano_Albamonte_Barber/filtros/ImageHandler.js
Esto sigue sin desaparecer!!

2023-11-13 01:11 UTC, UnirCs commented on Tema_2/Emiliano_Albamonte_Barber/filtros/package.json
Esto sigue sin desaparecer!!

2023-11-13 01:12 UTC, UnirCs requested changes
Elimina los archivos innecesarios por favor

2023-11-13 13:22 UTC, EMIsDev commented
acabo de hacerlo,  perdona por la tardanza estaba fuera y también me estoy intentando aclarar como funciona git con esta modaliad, gracias

2023-11-13 20:44 UTC, UnirCs commented on Tema_2/Emiliano_Albamonte_Barber/cinema/cinema.js
> +                break;
Viola la invariante

2023-11-13 20:44 UTC, UnirCs requested changes
Intenta quitar ese break que viola la invariante por favor!

2023-11-13 22:21 UTC, EMIsDev reviewed
he sacado la invariante, pero también debería sacar entonces el break y el return de las lineas 68 y 72? Entiendo el punto de la invariante que has explicado hoy en clase pero yo les daba uso para no seguir iterando en el bucle si ya una condición no se cumple.

2023-11-13 23:06 UTC, UnirCs commented
entiendo el por qué usas break, pero es mucho más limpio que el bucle termine por sí solo a que tú fuerces la parada. Cuando recurrimos a eso típicamente es porque no hemos sabido hacerlo de otra forma y ahí es donde hay que pensar de qué forma lo haríamos para que el bucle termine por sí solo de forma lógica

2023-11-14 00:14 UTC, UnirCs approved these changes
ok!

2023-11-14 00:15 UTC, merged