Tema1 - CV Task
UnirCs/DWFS-PER8408-2324 pull request #64
Opened 2023-11-12 18:50 UTC by JavierBelmonteRomero

2023-11-13 00:44 UTC, UnirCs commented on Tema_1/Javier_Belmonte_Romero/cv/index.html
> +        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" cross
En este ejercicio no se podía usar bootstrap, solo html + css

2023-11-13 00:45 UTC, UnirCs commented on Tema_2/Javier_Belmonte_Romero/cinema/cinema.js
> +            return false;
esto es muy poco elegante

2023-11-13 00:45 UTC, UnirCs commented on Tema_2/Javier_Belmonte_Romero/cinema/cinema.js
> +            break;
muy poco elegante y viola la invariante del bucle

2023-11-13 00:47 UTC, UnirCs requested changes
Hola Javier.

- Respeta por favor la estructura de carpetas, los ficheros deben estar dentro de la carpeta correspondiente al tipo de ejercicio, tal como indico en las instrucciones. Puedes ver ejemplos de compañeros.
- En el ejercicio del tema 1 usas bootstrap. En el del CV pedia usar HTML y CSS puro.
- En el ejercicio del tema 2 violas las invariantes de los bucles usando returns y breaks dentro de bucles. Además de dificultar la legibilidad del código, esto hace que algorítimicamente la solución no sea correcta

2023-11-15 20:55 UTC, JavierBelmonteRomero commented
Hola, 

Actualizo tareas. Respecto a la estructura de directorios, no veo el fallo. Los ficheros están dentro de las carpetas cv y cinema del Tema1 y Tema2 respectivamente.

Un saludo

2023-11-16 00:11 UTC, UnirCs approved these changes
Iteras más de lo necesario, ya que deberías finalizar también el bucle externo cuando j sea == al numero de tickets.
Pero es una sugerencia.

2023-11-16 00:12 UTC, merged