Ejercicios Tema 1 Albert Escoté Alvarez
UnirCs/DWFS-PER8408-2324 pull request #72
Opened 2023-11-13 20:26 UTC by albertescote-unir

2023-11-13 20:55 UTC, UnirCs commented on Tema_1/albertescotealvarez/cv/index.html
> +        <p style="margin-left: 20px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer augue felis, laoreet eget ultrices eu, imperdiet sed tellus.</p>
estilos inline nooo :(

2023-11-13 20:55 UTC, UnirCs requested changes
Elimina estilos css inline

2023-11-14 09:53 UTC, albertescote-unir commented on Tema_1/albertescotealvarez/cv/index.html
> +        <p style="margin-left: 20px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer augue felis, laoreet eget ultrices eu, imperdiet sed tellus.</p>
Ay! Perdón, se me pasó. Ya lo he arreglado.

2023-11-16 00:12 UTC, UnirCs approved these changes
ok!

2023-11-16 00:12 UTC, merged