Actualización Talleres
UnirCs/DWFS-PER8408-2324 pull request #73
Opened 2023-11-13 20:48 UTC by BMV-SIETE

Actualizacion de ejercicios Clase 1 y Clase 2.

2023-11-13 20:56 UTC, UnirCs commented on Tema_2/00_Resources/Codigo de ejemplo/00_Exec_Dilemma_Interpreted.js
Este archivo no lo puedes modificar

2023-11-13 20:57 UTC, UnirCs commented on Tema_2/.vscode/launch.json
este no hay que subirlo

2023-11-13 20:57 UTC, UnirCs commented on Tema_2/Breiner Medina Villero/CINEMA/cinema2.js
> +            break;
esto viola la invariante del bucle

2023-11-13 20:58 UTC, UnirCs requested changes
Quita los archivos que no son necesarios por favor, en cuanto a los ejercicios, los 2 primeros estan bien.

El del tema 2 tienes que reformularlo para no violar la invariante del bucle

2023-11-14 00:47 UTC, BMV-SIETE commented
Ok procederé a realizar ajustes solicitados.

2023-11-14 00:47 UTC, closed without merging