Tema 1 por Fernando Rodriguez
UnirCs/DWFS-PER8408-2324 pull request #85
Opened 2023-11-14 04:58 UTC by Fer1196

Ejercicio 1

2023-11-16 00:19 UTC, UnirCs commented on .vscode/settings.json
Este fichero no se puede incluir en la PR, esta fuera de tu carpeta

2023-11-16 00:19 UTC, UnirCs requested changes
Los ejercicios estan bien pero incluyes archivos en la pr que estan fuera de la zona en la que se te permite incluir ficheros.

2023-11-16 01:18 UTC, Fer1196 commented
He resuleto el conflicto me lo puede revisar otra vez para mergearlo por favor

2023-11-16 08:32 UTC, UnirCs commented on .gitignore
Este fichero sigue en la PR, no puede estar

2023-11-18 03:26 UTC, Fer1196 commented
Listo ahora si ya esta todo correcto, he corregido eso del git ignore y adicional he subido otros ejercicios. Mil disculpas

2023-11-19 21:53 UTC, UnirCs commented on Tema_2/00_Resources/filtros/actividad.js
No borres mi archivo por favor :(

2023-11-19 21:53 UTC, UnirCs requested changes
Tienes los ejercicios bien Fernando, pero ahora en el tema 2 borraste mi archivo de resources. Si te acepto el pr el resto de compañeros que quieran usarlo no lo verán. Reestablecelo por favor y mergeamos

2023-11-19 22:05 UTC, Fer1196 commented
Listo profe ahora si ya puse el archivo correcto en Resources. 
No importa que use un amend para subir los cambios?
![image](https://github.com/UnirCs/DWFS-PER8408-2324/assets/29605687/cbd40b79-65fc-41d3-80cd-26e9d32734cf)

2023-11-19 22:15 UTC, UnirCs approved these changes
Está un poco diferente al que yo subí, pero no pasa nada lo restauro yo. vamos a por la siguiente semana!

2023-11-19 22:15 UTC, merged