Ejercicios voluntarios tema 2
UnirCs/DWFS-PER8408-2324 pull request #87
Opened 2023-11-14 12:48 UTC by gmarcg00

2023-11-16 00:23 UTC, UnirCs commented on Tema_2/Guillermo_Marcos_García/cinema/cinema.js
> +                return availableSeats;
Viola la invariante del bucle

2023-11-16 00:23 UTC, UnirCs requested changes
El ejercicio de filtros está bien.
En el del cine se viola la invariante con ese return dentro de 2 bucles.

2023-11-16 10:17 UTC, gmarcg00 commented
Cambios realizados para no violar la invariante del bucle

2023-11-19 21:54 UTC, UnirCs approved these changes
OK!

2023-11-19 21:54 UTC, merged