Tema 2 y Tema 3
UnirCs/DWFS-PER8408-2324 pull request #91
Opened 2023-11-14 23:05 UTC by jcanta2001

2023-11-16 00:27 UTC, UnirCs commented on Tema_2/Javier_Cantalapiedra_Artiaga/Cinema/cinema.js
> +                return asientos;
viola la invariante

2023-11-16 00:28 UTC, UnirCs requested changes
Ejercicio de filtros y los del t3 ok.
En el t2 del cine, violas la invariante con ese return dentro de 2 bucles.

2023-11-19 21:55 UTC, UnirCs commented on Tema_2/Javier_Cantalapiedra_Artiaga/Cinema/cinema.js
> +                return asientos;
Esto sigue sin solucionarse

2023-11-19 23:37 UTC, jcanta2001 commented on Tema_2/Javier_Cantalapiedra_Artiaga/Cinema/cinema.js
> +                return asientos;
No me había llegado el correo anterior, con el nuevo commit ya debería de estar resuelto

2023-11-20 17:05 UTC, UnirCs approved these changes
OK!

2023-11-20 17:05 UTC, merged