Se dejan Archivos de ejemplo en Rama Master como estaban
UnirCs/DWFS-PER8408-2324 pull request #99
Opened 2023-11-16 02:52 UTC by BMV-SIETE

2023-11-16 08:33 UTC, UnirCs commented on Tema_2/00_Resources/Codigo de ejemplo/00_Exec_Dilemma_Compiled.js
Este fichero no se puede modificar

2023-11-16 08:33 UTC, UnirCs requested changes
No se pueden modificar mis archivos

2023-11-16 21:56 UTC, BMV-SIETE commented
Se ajusta código de ejemplo modificado equivocadamente, al confundir la rama Master con mi repositorio local.

2023-11-19 21:57 UTC, UnirCs approved these changes
ok!

2023-11-19 21:57 UTC, merged